### ISSUE TITLE
Getting same response from statusQueryGetUri in case of failures  

### ISSUE THREAD

**Issue by akshaykumars10** [microsoft/durabletask-java#113]
We get this error message for any kind of error in our orchestrator function. Error received:
`{
Message: "One or more of the arguments submitted is incorrect",
ExceptionMessage: "address (Parameter 'Missing account name information inside path style uri. Path style uris should be of the form http://<IPAddressPlusPort>/<accountName>')",
ExceptionType: "System.ArgumentException",
StackTrace: "   at Microsoft.WindowsAzure.Storage.Core.Util.NavigationHelper.GetServiceClientBaseAddress(Uri addressUri, Nullable1 usePathStyleUris)
   at Microsoft.WindowsAzure.Storage.Core.Util.NavigationHelper.GetServiceClientBaseAddress(StorageUri addressUri, Nullable1 usePathStyleUris)
   at Microsoft.WindowsAzure.Storage.Blob.CloudBlob.ParseQueryAndVerify(StorageUri address, StorageCredentials credentials)
   at Microsoft.WindowsAzure.Storage.Blob.CloudBlob..ctor(StorageUri blobAbsoluteUri, Nullable1 snapshotTime, StorageCredentials credentials)
   at Microsoft.WindowsAzure.Storage.Blob.CloudBlockBlob..ctor(StorageUri blobAbsoluteUri, Nullable1 snapshotTime, StorageCredentials credentials)
   at Microsoft.WindowsAzure.Storage.Blob.CloudBlockBlob..ctor(Uri blobAbsoluteUri, Nullable1 snapshotTime, StorageCredentials credentials)
   at Microsoft.WindowsAzure.Storage.Blob.CloudBlockBlob..ctor(Uri blobAbsoluteUri, StorageCredentials credentials)
   at DurableTask.AzureStorage.Storage.Blob..ctor(AzureStorageClient azureStorageClient, CloudBlobClient blobClient, Uri blobUri) in /_/src/DurableTask.AzureStorage/Storage/Blob.cs:line 42
   at DurableTask.AzureStorage.Storage.AzureStorageClient.GetBlobReference(Uri blobUri) in /_/src/DurableTask.AzureStorage/Storage/AzureStorageClient.cs:line 88
   at DurableTask.AzureStorage.MessageManager.DownloadAndDecompressAsBytesAsync(Uri blobUri) in /_/src/DurableTask.AzureStorage/MessageManager.cs:line 209
   at DurableTask.AzureStorage.MessageManager.FetchLargeMessageIfNecessary(String message) in /_/src/DurableTask.AzureStorage/MessageManager.cs:line 123
   at DurableTask.AzureStorage.Tracking.AzureTableTrackingStore.ConvertFromAsync(OrchestrationInstanceStatus orchestrationInstanceStatus, String instanceId) in /_/src/DurableTask.AzureStorage/Tracking/AzureTableTrackingStore.cs:line 568
   at DurableTask.AzureStorage.Tracking.AzureTableTrackingStore.FetchInstanceStatusInternalAsync(String instanceId, Boolean fetchInput) in /_/src/DurableTask.AzureStorage/Tracking/AzureTableTrackingStore.cs:line 451
   at DurableTask.AzureStorage.Tracking.AzureTableTrackingStore.GetStateAsync(String instanceId, String executionId, Boolean fetchInput) in /_/src/DurableTask.AzureStorage/Tracking/AzureTableTrackingStore.cs:line 420
   at DurableTask.AzureStorage.Tracking.AzureTableTrackingStore.GetStateAsync(String instanceId, Boolean allExecutions, Boolean fetchInput) in /_/src/DurableTask.AzureStorage/Tracking/AzureTableTrackingStore.cs:line 414
   at DurableTask.AzureStorage.AzureStorageOrchestrationService.GetOrchestrationStateAsync(String instanceId, Boolean allExecutions, Boolean fetchInput) in /_/src/DurableTask.AzureStorage/AzureStorageOrchestrationService.cs:line 1680
   at Microsoft.Azure.WebJobs.Extensions.DurableTask.AzureStorageDurabilityProvider.GetOrchestrationStateWithInputsAsync(String instanceId, Boolean showInput) in D:\a\_work\1\s\src\WebJobs.Extensions.DurableTask\AzureStorageDurabilityProvider.cs:line 80
   at Microsoft.Azure.WebJobs.Extensions.DurableTask.DurableClient.Microsoft.Azure.WebJobs.Extensions.DurableTask.IDurableOrchestrationClient.GetStatusAsync(String instanceId, Boolean showHistory, Boolean showHistoryOutput, Boolean showInput) in D:\a\_work\1\s\src\WebJobs.Extensions.DurableTask\ContextImplementations\DurableClient.cs:line 470
   at Microsoft.Azure.WebJobs.Extensions.DurableTask.HttpApiHandler.HandleGetStatusRequestAsync(HttpRequestMessage request, String instanceId, Nullable1 returnInternalServerErrorOnFailure, IDurableOrchestrationClient existingClient) in D:\a\_work\1\s\src\WebJobs.Extensions.DurableTask\HttpApiHandler.cs:line 635
   at Microsoft.Azure.WebJobs.Extensions.DurableTask.HttpApiHandler.HandleRequestAsync(HttpRequestMessage request) in D:\a\_work\1\s\src\WebJobs.Extensions.DurableTask\HttpApiHandler.cs:line 376"
}`

Error received with python SDK for the same kind of failures in the orchestrator function:
`{
name: "WorkflowOrchestrator",
instanceId: "akshay",
runtimeStatus: "Failed",
input: "{}",
customStatus: null,
output: "Orchestrator function 'WorkflowOrchestrator' failed: 'NoneType' object has no attribute 'get'",
createdTime: "2023-02-15T10:04:01Z",
lastUpdatedTime: "2023-02-15T10:04:03Z"
}`
Can we please fix this?

**Comment by cgillum** [comment]
@akshaykumars10 can you please open an issue in the [Python SDK](https://github.com/Azure/azure-functions-durable-python)? This repo is for the Java SDK.

Also, when opening issues there, please provide more information, such as the name of the app, region, and/or an orchestration instance ID that the team can use to verify the problem you're encountering.

**Comment by akshaykumars10** [comment]
The issue is with the Java SDK only. In python, it works fine. I had this on my local setup. I will re-create this in one of my java apps in the portal and share the details. Thanks!

**Comment by cgillum** [comment]
@akshaykumars10 I see - you didn't provide any context in your post, so it was difficult to understand what the error message was referring to. Are you seeing this when you try to invoke a status query URI for an orchestrations?

I suspect this may be related to an issue in the Azure Storage provider for Durable Functions related to how large inputs or output payloads are handled ("large" means > 40KB).

@bachuv I recall that you had a fix for a similar issue related to blob URL handling in one of the PRs you were working on. Do you remember which PR this was? I'm wondering if we need to get that fix would apply to this specific case.

**Comment by bachuv** [comment]
@cgillum, yes it was [#853](https://github.com/Azure/durabletask/pull/853) and the issue and fix are described in the comment [here](https://github.com/Azure/durabletask/pull/853#discussion_r1087081311). I added the fix as a part of the distributed tracing PRs, but I can create a new PR to separate it out.

**Comment by cgillum** [comment]
Thanks @bachuv - if you wouldn't mind, it would be great to have that fix in a separate PR so that we can merge it independently from distributed tracing and get the fix out sooner.

**Comment by bachuv** [comment]
No problem, I created the PR - https://github.com/Azure/durabletask/pull/867. I added you as a reviewer.

**Comment by akshaykumars10** [comment]
Thanks for looking into this @cgillum @bachuv

**Comment by lilyjma** [comment]
@akshaykumars10 - can you still reproduce this problem? This should've been fixed in the latest DF extension version. Could you find out what version of the DF extension you're using by running your app locally with Core Tools?

**Comment by akshaykumars10** [comment]
This is fixed now. Thanks Team
cc: @lilyjma
